name = "OpenMDAOCore"
uuid = "24d19c10-6eee-420f-95df-4537264b2753"
authors = ["Daniel Ingraham <d.j.ingraham@gmail.com>"]
version = "0.3.1"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.8.5"
