name = "OpenMDAO"
uuid = "2d3f9b48-ba2d-11e9-1a3f-97e029ee3d3c"
authors = ["Ingraham, Daniel James (GRC-LTV0) <daniel.j.ingraham@nasa.gov>"]
version = "0.3.2"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
OpenMDAOCore = "24d19c10-6eee-420f-95df-4537264b2753"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
OpenMDAOCore = "0.2.10"
