[project]
name = 'example_python_package_openmdao_jl'
description = "Example Python package using OpenMDAOCore.jl"
version = "0.1.0"

dependencies = [
    "openmdao~=3.26",
    "juliapkg~=0.1.10",
    "juliacall~=0.9.13",
    "omjlcomps>=0.3.0",
]
