name: Tests

on:
  pull_request:
    branches:
      - pythoncall_juliacall
  push:
    branches:
      - pythoncall_juliacall
    tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: OpenMDAOCore.jl Tests
        shell: julia --color=yes --project=--project=$(mktemp -d) {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path="./julia/OpenMDAOCore.jl"))
          Pkg.update()
          Pkg.test()
        env:
              JULIA_PKG_USE_CLI_GIT: 'true'
