name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'

jobs:
  julia:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version:
          - '1' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/add-julia-registry@v1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          registry: dingraha/DanielIngrahamRegistry
        env:
              JULIA_PKG_USE_CLI_GIT: 'true'
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - name: OpenMDAOCore.jl Tests
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.activate("./julia/OpenMDAOCore.jl")
          Pkg.update()
          Pkg.test()
        env:
              JULIA_PKG_USE_CLI_GIT: 'true'
      - name: OpenMDAO.jl Tests
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.activate("./julia/OpenMDAO.jl")
          Pkg.update()
          Pkg.test()
        env:
              JULIA_PKG_USE_CLI_GIT: 'true'

  python:
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        julia-version:
          - '1' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
        os:
          - ubuntu-latest
        arch:
          - x64
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/add-julia-registry@v1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          registry: dingraha/DanielIngrahamRegistry
        env:
              JULIA_PKG_USE_CLI_GIT: 'true'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: omjlcomps install
        run: |
          python -m pip install --upgrade pip
          pip install -e ./python
          python -c "import juliapkg; juliapkg.resolve()"
        env:
              JULIA_PKG_USE_CLI_GIT: 'true'
      - name: omjlcomps tests
        run: |
          python ./python/omjlcomps/test/test_julia_explicit_comp.py
          python ./python/omjlcomps/test/test_julia_implicit_comp.py
        env:
              JULIA_PKG_USE_CLI_GIT: 'true'
